version: '3.8'

services:
    database:
      build:
        context: "./docker/postgres"
      container_name: 'postgres'
      restart: 'always'
      ports:
        - "5432:5432"
      environment:
        POSTGRES_DB: ${DATABASE_NAME}
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

